name: TheEvent580-2
version: '${version}'
main: fr.thefox580.theevent5802.TheEvent580_2
api-version: '1.20'
authors: [TheFox580]

commands:
  starttp:
    description: Tp after start
    permission: op
    permission-message: "&cYou do not have the required permissions to teleport the players in the decision crystal"

  gametp:
    description: Tp after games
    permission: op
    permission-message: "&cYou do not have the required permissions to teleport the players in the decision crystal after a game"

  pronouns:
    description: Changes player's pronouns

  damage:
    description: Toggles damage
    permission: op
    permission-message: "&cYou do not have the required permissions to toggle damage"

  showpronouns:
    description: Toggles pronouns before a message

  minecraftle:
    description: Starts a Minecraftle

  craft:
    description: Opens the crafting table

  announcement:
    description: Makes an announcement in the chat
    aliases:
      - "bc"
      - "broadcast"
      - "announce"
      - "announcements"
      - "alert"
      - "alerts"
    permission: op
    permission-message: "&cYou do not have the required permissions to make an announcement in the chat"