name: TheEvent580-2
version: '${version}'
main: fr.thefox580.theevent5802.TheEvent580_2
api-version: '1.21'
authors: [TheFox580]

commands:
  starttp:
    description: Tp after start
    permission: op
    permission-message: "&cYou do not have the required permissions to teleport the players in the decision crystal"

  gametp:
    description: Tp after games
    permission: op
    permission-message: "&cYou do not have the required permissions to teleport the players in the decision crystal after a game"

  pronouns:
    description: Changes player's pronouns

  customcolor:
    description: Gives a player a custom color
    permission: op
    permission-message: "&cYou do not have the required permissions to give someone a custom color"

  damage:
    description: Toggles damage
    permission: op
    permission-message: "&cYou do not have the required permissions to toggle damage"

  showpronouns:
    description: Toggles pronouns before a message

  minecraftle:
    description: Starts a Minecraftle

  craft:
    description: Opens the crafting table

  announcement:
    description: Makes an announcement in the chat
    aliases:
      - "bc"
      - "broadcast"
      - "announce"
      - "announcements"
      - "alert"
      - "alerts"
    permission: op
    permission-message: "&cYou do not have the required permissions to make an announcement in the chat"

  stats:
    description: Creates/Shows a statistic for a player

  db:
    description: Modifies database infos
    permission: op
    permission-message: "&cYou do not have the required permissions to interact with the database"

  toast:
    description: Creates a toast for a/all player/s
    permission: op
    permission-message: "&cYou do not have the required permissions to create a toast"