name: TheEvent580-2
version: '${version}'
main: fr.thefox580.theevent5802.TheEvent580_2
api-version: '1.21'
authors: [TheFox580]

commands:
  start:
    description: Starts the event
    permission: op
    permission-message: "&cYou do not have the required permissions to START THE EVENT"

  spawn:
    description: Teleports the player to spawn

  pronouns:
    description: Changes player's pronouns

  customcolor:
    description: Gives yourself a custom color

  damage:
    description: Toggles damage
    permission: op
    permission-message: "&cYou do not have the required permissions to toggle damage"

  showpronouns:
    description: Toggles pronouns before a message

  minecraftle:
    description: Starts a Minecraftle

  craft:
    description: Opens the crafting table

  announcement:
    description: Makes an announcement in the chat
    aliases:
      - "bc"
      - "broadcast"
      - "announce"
      - "announcements"
      - "alert"
      - "alerts"
    permission: op
    permission-message: "&cYou do not have the required permissions to make an announcement in the chat"

  stats:
    description: Creates/Shows a statistic for a player

  db:
    description: Modifies database infos
    permission: op
    permission-message: "&cYou do not have the required permissions to interact with the database"

  points:
    description: Gets / modifies a player's points
    permission: op
    permission-message: "&cYou do not have the required permissions to interact with points"

  test:
    description: Executes the test
    permission: op
    permission-message: "&cYou do not have the required permissions to test stuff, what did you think?"

  sets:
    description: Shows a menu will items in the shop

  variables:
    description: Perform operations on variables
    permission: op
    permission-message: "&cYou do not have the required permissions to perform operations on variables"

  version:
    description: Shows in chat the plugin version

  players:
    description: Gets / Modifies the player list
    permission: op
    permission-message: "&cYou do not have the required permission to modify the player list"

  spectators:
    description: Gets / Modifies the spectator list
    permission: op
    permission-message: "&cYou do not have the required permission to modify the spectator list"

  reloadcfg:
    description: Reloads the config
    permission: op
    permission-message: "&cYou cannot reload the config"

  timer:
    description: Interacts with the timer
    permission: op
    permission-message: "&cYou cannot interact with the timer"

  mute:
    description: Mutes the whole server / a specific player
    permission: op
    permission-message: "&cYou cannot mute anyone"

  lb:
    description: shows a player the whole event leaderboard
    aliases:
      - "leaderboard"
      - "leaderb"
      - "leadb"

  specmenu:
    description: opens the spectator menu to teleport to a player

  fly:
    description: toggles fly mode if you have access to it

  showblocks:
    aliases:
      - "blocks"
      - "showblock"
    description: toggles if you see the block name above your hotbar or not